---
  name: Trigger dispatch
  on: [create,public]
  jobs:
    send-request:
      runs-on: ubuntu-latest
      steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          repository: DevSecOps-test-304/central
          token: ${{secrets.GIT_PAT}}
          event-type: repo-public
          client-payload: '{"repo":"${{github.event.repository.name}}"}'
